
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rain
 */
public class gymsystem extends javax.swing.JFrame {

   ImageIcon logo = new ImageIcon( "Gym.png");
    public gymsystem() {
        initComponents();
        setTitle("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel(logo);
        jPanel1 = new javax.swing.JPanel();
        adminUsername = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel1.setSize(650, 450);
        jLabel1.setText(null);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new Color(98, 39, 24));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        adminUsername.setEditable(false);
        adminUsername.setForeground(Color.lightGray);
        adminUsername.setText("Enter Admin Username");
        adminUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adminUsernameFocusLost(evt);
            }
        });
        adminUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminUsernameMouseExited(evt);
            }
        });
        adminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameActionPerformed(evt);
            }
        });
        adminUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminUsernameKeyPressed(evt);
            }
        });

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Show Password");
        jCheckBox1.setVisible(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordFieldMouseExited(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        passwordField.setEchoChar((char)0);
        passwordField.setText("Enter Password");
        passwordField.setForeground(Color.lightGray);
        passwordField.setEditable(false);

        if("".equals(passwordField.getText())){
            passwordField.setEchoChar((char)0);
            passwordField.setText("Enter Password");
            passwordField.setForeground(Color.lightGray);
            passwordField.setEditable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1)
                            .addComponent(adminUsername)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            passwordField.setEchoChar((char)0);
        }else{
            if("Enter Password".equals(passwordField.getText())){
                passwordField.setEchoChar((char)0);
            }else{
            passwordField.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void adminUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUsernameMouseClicked
        if("Enter Admin Username".equals(adminUsername.getText())){
            adminUsername.setText("");
            adminUsername.setForeground(Color.black);
            adminUsername.setEditable(true);
        }
    }//GEN-LAST:event_adminUsernameMouseClicked

    private void adminUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUsernameMouseExited
       
    }//GEN-LAST:event_adminUsernameMouseExited

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if("Enter Password".equals(passwordField.getText())){
                passwordField.setText("");
                passwordField.setForeground(Color.black);
                passwordField.setEditable(true);
                passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void passwordFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseExited
       
    }//GEN-LAST:event_passwordFieldMouseExited

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
         if("Admin1".equals(adminUsername.getText()) && "Admin123".equals(passwordField.getText())){
            dispose();
            NewMember x = new NewMember();
                x.setVisible(true);
                x.setLocationRelativeTo(null);
         }else{
            JOptionPane.showMessageDialog(new JFrame(), "Incorrenct Username or Password", "Dialog", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void adminUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminUsernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if("Admin1".equals(adminUsername.getText()) && "Admin123".equals(passwordField.getText())){
            dispose();
            NewMember x = new NewMember();
                x.setVisible(true);
                x.setLocationRelativeTo(null);
         }else{
            JOptionPane.showMessageDialog(new JFrame(), "Incorrenct Username or Password", "Dialog", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_adminUsernameKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetterOrDigit(c)){
            jCheckBox1.setVisible(true);
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if("Admin1".equals(adminUsername.getText()) && "Admin123".equals(passwordField.getText())){
            dispose();
            NewMember x = new NewMember();
                x.setVisible(true);
                x.setLocationRelativeTo(null);
         }else{
            JOptionPane.showMessageDialog(new JFrame(), "Incorrenct Username or Password", "Dialog", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void adminUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminUsernameFocusLost
        if("".equals(adminUsername.getText())){
            adminUsername.setText("Enter Admin Username");
            adminUsername.setForeground(Color.lightGray);
            adminUsername.setEditable(false);
        }
    }//GEN-LAST:event_adminUsernameFocusLost

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        adminUsername.setFocusable(false);
        adminUsername.setFocusable(true);
        passwordField.setFocusable(false);
        passwordField.setFocusable(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
         if("".equals(passwordField.getText())){
            passwordField.setEchoChar((char)0);
            passwordField.setText("Enter Password");
            passwordField.setForeground(Color.lightGray);
            passwordField.setEditable(false);
            jCheckBox1.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        adminUsername.setFocusable(false);
        adminUsername.setFocusable(true);
        passwordField.setFocusable(false);
        passwordField.setFocusable(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gymsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gymsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gymsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gymsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gymsystem x = new gymsystem();
                x.setVisible(true);
                x.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminUsername;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
